import { faqEn } from "../faq";
import { heroDemoEn } from "../landing-hero-demo";
import type { LandingContent } from "./types";
import { landingTr } from "./tr";

export const landingEn: LandingContent = {
  ...landingTr,
  meta: {
    title: "ROUTEPOL | The route that guides you in Poland.",
    description:
      "ROUTEPOL — The route that guides you in Poland. For entrepreneurs from Turkey and Turkish or foreign companies in Poland: official letters, documents and admin tracking. Summarised in your language. Clear next step. Also: trade advisory.",
  },
  brand: {
    name: "ROUTEPOL",
    tagline: "The route that guides you in Poland.",
    secondName: "ROUTEPOL",
    secondLineHint: "Turkey · Poland",
  },
  nav: [
    { id: "hizmetler", label: "Services", href: "/hizmetler" },
    { id: "paketler", label: "Packages", href: "/hizmetler#paketler" },
    { id: "danismanlik", label: "Advisory", href: "/danismanlik" },
    { id: "hakkimizda", label: "About", href: "/hakkimizda" },
    { id: "rehber", label: "Guide", href: "/rehber" },
    { id: "sss", label: "FAQ", href: "#sss" },
    { id: "iletisim", label: "Contact", href: "#iletisim" },
  ],
  headerCta: "Apply",
  accountLink: "Sign in",
  hero: {
    eyebrow: "Turkey · Poland",
    title: "Poland admin, in one place.",
    subtitle:
      "We summarise official letters in your language. Deadlines and next steps stay clear. Document tracking with us. Decisions with you.",
    valueLine:
      "We are not a law firm. Registration and legal representation stay with the lawyer partner. Trade advisory is a separate service line.",
    ctaPrimary: "View packages",
    ctaPrimaryHref: "/hizmetler#paketler",
    ctaSecondary: "Trade advisory",
    ctaSecondaryHref: "/danismanlik",
    demo: heroDemoEn,
  },
  bridge: {
    eyebrow: "How it works",
    title: "The authority writes. We track. You decide.",
    intro:
      "Poland admin files gather in one place. Language, deadline and next step do not get lost.",
    lanes: [
      {
        id: "kurum",
        label: "Authority",
        body: "An office, ZUS, tax office or bank sends an official request — usually in Polish.",
      },
      {
        id: "pol-turk",
        label: "ROUTEPOL",
        body: "We summarise the letter in your language. We clarify the deadline and next step. We keep the file moving.",
      },
      {
        id: "siz",
        label: "You",
        body: "You approve scope. You supply documents. Decisions and signatures stay with you or your authorised partner.",
      },
    ],
    lawyerNote:
      "Legal advice, representation and registration stay with the lawyer partner. ROUTEPOL does not enter that line.",
    serviceLine: {
      title: "Trade advisory",
      body: "Market visibility, counterparty mapping, meetings and quote compilation. Offered separately from admin tracking.",
      ctaLabel: "Explore",
      href: "/danismanlik",
    },
  },
  audiences: {
    eyebrow: "Who it’s for",
    title: "Service lines",
    intro:
      "Corporate investment, local operations, education administration and individual office matters run to the same operating standard: written scope, language bridge, tracking, coordination with the authorised partner.",
    items: [
      {
        id: "yatirimci",
        icon: "Building2",
        title: "Investment and company formation from Turkey",
        body: "Turkish operators investing in Poland: limited company / branch / activity and first-year administration. Process map, file preparation and initiation of the lawyer–notary–KRS track. Registration remains with the authority and the lawyer partner.",
        points: [
          "Pre-decision: administrative load of structures, sequence, HQ checklist",
          "Formation period: lawyer-partner appointment, document gaps, post-KRS NIP/REGON/VAT-UE/bank",
          "Operations: letter summaries, HQ–Poland bridge, admin execution under POA",
        ],
        ctaLabel: "Investment and formation advisory",
        href: "/hizmetler/kurulum",
      },
      {
        id: "isletme",
        icon: "Store",
        title: "Turkish SMEs / sole traders in PL",
        body: "Hospitality, logistics / transport, wholesale, construction — US/ZUS/KRS and activity papers; bridge to the lawyer partner.",
        points: [
          "What is requested and by when",
          "Logistics / field activity letters and appointments",
          "Clear note for the accountant; legal advice stays with the lawyer partner",
        ],
        ctaLabel: "Business services",
        href: "/hizmetler/isletme",
      },
      {
        id: "egitim",
        icon: "GraduationCap",
        title: "University & education processes",
        body: "Administrative guidance around higher-education correspondence: document order, letter summaries, family–institution language bridge. Not an admission guarantee.",
        points: [
          "Enrolment document checklist",
          "University / dorm letter explanation",
          "Same standard for applicants, families or education units",
        ],
        ctaLabel: "Education guidance",
        href: "/hizmetler/egitim",
      },
      {
        id: "sahis",
        icon: "User",
        title: "Turks in Poland — individuals",
        body: "Government offices: document tracking, remote / phone information, residence card and driving-licence processes. No decision guarantee.",
        points: [
          "Exchange to a Polish driving licence — steps, papers, appointment (decision is the office’s)",
          "Residence card: letter summary, missing papers, status tracking",
          "Translation need: language bridge; sworn translator referred, not performed by us",
        ],
        ctaLabel: "Individual admin support",
        href: "/hizmetler/eslik#sahis",
      },
    ],
  },
  fieldSupport: {
    eyebrow: "On-site accompaniment",
    title: "Inter-office support for companies and individuals",
    intro:
      "Alongside letter packages: offices, bank, PESEL, licence. Written packages and on-site accompaniment via the contact form. Languages: TR / PL / EN / RU / UK.",
    items: [
      {
        id: "eslik-firma",
        icon: "Building2",
        title: "Company",
        body: "SMEs and TR investment companies: bank KYC, US/ZUS/KRS, logistics paperwork, employer-side files.",
        points: [
          "Business account / KYC and office visits",
          "Logistics activity letters and appointments",
          "Optional accompaniment at the office / bank",
        ],
        ctaLabel: "Company accompaniment",
        href: "/hizmetler/eslik#firma",
      },
      {
        id: "eslik-sahis",
        icon: "User",
        title: "Individual",
        body: "Turks in Poland: offices, PESEL, licence exchange, residence card — remote, phone or on site.",
        points: [
          "Licence / residence card: checklist, appointment, status (decision is the office’s)",
          "Phone and remote information",
          "Optional accompaniment; TR / PL / EN / RU / UK",
        ],
        ctaLabel: "Individual accompaniment",
        href: "/hizmetler/eslik#sahis",
      },
    ],
    disclaimer:
      "No guarantee of account, PESEL, licence or medical outcome. Legal work stays with the lawyer partner.",
    hubCta: "Accompaniment page",
    hubHref: "/hizmetler/eslik",
  },
  categories: {
    eyebrow: "Service areas",
    title: "Corporate service areas",
    intro:
      "Three paid packages plus investment/formation advisory, the business desk, education administration and the individual office line. All of it is administrative advisory — not legal advice, KRS registration or a tax signature.",
    items: [
      {
        id: "yazi-ozeti",
        icon: "FileText",
        title: "Official letter summary",
        body: "One letter: PL / EN / TR explanation, deadline, who does what.",
        packageSlug: "tek-yazi",
        href: "/hizmetler/tek-yazi",
        ctaLabel: "Single letter",
        badge: "Package",
      },
      {
        id: "evrak-takip",
        icon: "Mail",
        title: "Document & admin tracking",
        body: "Letters through the month; Stripe subscription (auto-renew). Period fee applies even with no letters. Status on the case page / Account; clear overage.",
        packageSlug: "aylik-paket",
        href: "/hizmetler/aylik-paket",
        ctaLabel: "Monthly subscription",
        badge: "Package",
      },
      {
        id: "vekaletli",
        icon: "FileSignature",
        title: "Admin execution with POA",
        body: "Document and appointment coordination under notarial admin POA. Formation and intensive periods.",
        packageSlug: "surec-yonetimi",
        href: "/hizmetler/surec-yonetimi",
        ctaLabel: "POA package",
        badge: "Package",
      },
      {
        id: "surec-yonlendirme",
        icon: "Map",
        title: "Investment, formation and process advisory",
        body: "Turkish operators: Polish company formation and activity launch — document sequence, preparation of the lawyer–notary track, post-registration administration. We do not register the company in your name.",
        href: "/hizmetler/kurulum",
        ctaLabel: "Formation advisory",
        badge: "Consult",
      },
      {
        id: "sahis-idari",
        icon: "User",
        title: "Individuals — offices, licence, residence",
        body: "Turks in Poland: tracking, phone, licence exchange, residence card. No decision guarantee.",
        href: "/hizmetler/eslik#sahis",
        ctaLabel: "Individual track",
        badge: "Consult",
      },
      {
        id: "egitim-yonlendirme",
        icon: "GraduationCap",
        title: "University / education guidance",
        body: "Documentation order and process map for education paths.",
        href: "/hizmetler/egitim",
        ctaLabel: "Education page",
        badge: "Consult",
      },
    ],
  },
  packages: {
    eyebrow: "Packages",
    title: "Orderable packages",
    intro:
      "Four packages: Single letter, Monthly tracking (subscription), POA execution (subscription), On-site accompaniment. Monthly packages renew on the card automatically. A case opens after payment.",
    applyLabel: "Apply",
    detailLabel: "Details",
    talkLabel: "Write first — ask before choosing a package",
    talkHref: "#iletisim",
    featuredStory: {
      title: "Through the month",
      steps: [
        "Incoming letters summarised in your language",
        "Deadline and next step clarified",
        "Tracked on your case page",
      ],
    },
  },
  process: {
    eyebrow: "How it works",
    title: "Two paths — package or on-site accompaniment",
    intro:
      "Have a letter — buy a letter package. On-site accompaniment (office / bank / urząd) is a separate package on the site — city required; travel outside the city is separate. Phone consultation is not available right now; general questions use the contact form.",
    paidPathTitle: "Four steps for paid packages",
    steps: [
      {
        title: "Pick a package",
        body: "Letter packages: PDF / photo. On-site: city and a short briefing.",
      },
      {
        title: "Payment",
        body: "Stripe. Your private case link arrives by email.",
      },
      {
        title: "Explain + track",
        body: "What was asked, deadline, next step — in your language.",
      },
      {
        title: "Result",
        body: "Download from your case page. No file attached to email.",
      },
    ],
    consultPathTitle: "On-site accompaniment (office / bank)",
    consultPathBody:
      "Half-day package: 450 zł, one office / one visit. Poland-wide base fee; out-of-city travel agreed separately. No decision guarantee. Heavy admin periods use the separate POA package.",
    consultSteps: [
      {
        title: "Pick the package",
        body: "On the application: On-site accompaniment; city and visit purpose.",
      },
      {
        title: "Payment",
        body: "450 zł half day — Stripe. Operator confirms the slot.",
      },
      {
        title: "Visit day",
        body: "Language bridge at the office / bank / urząd; not legal representation.",
      },
      {
        title: "Status note",
        body: "What happened, what is next — on your case page.",
      },
    ],
    ctaPackage: "Go to packages",
    ctaConsult: "Apply — on-site",
  },
  cases: {
    eyebrow: "Examples",
    title: "Common situations",
    intro: "Not a guarantee of an official decision or legal outcome.",
    tabs: [
      {
        id: "us-zus",
        label: "Tax / ZUS",
        title: "Tax office or ZUS letter",
        bullets: [
          "Upload the letter (single letter or monthly plan)",
          "Summary: request, deadline, annexes",
          "Clear note for your accountant",
          "Lawyer bridge if needed",
        ],
        ctaLabel: "Packages",
        href: "/hizmetler#paketler",
      },
      {
        id: "krs",
        label: "Company register",
        title: "KRS / company changes",
        bullets: [
          "Document sequence",
          "Appointment coordination (POA package)",
          "Status in your language",
          "Decisions stay with lawyer / authorised person",
        ],
        ctaLabel: "POA package",
        href: "/hizmetler/surec-yonetimi",
      },
      {
        id: "calisan",
        label: "Employee stay",
        title: "Employer-side residence file",
        bullets: [
          "Employer-side checklist (single letter or monthly tracking)",
          "Missing-document check",
          "Guides: letters, packages, formation, individuals, MOS",
          "Representation with the lawyer partner",
        ],
        ctaLabel: "Business services",
        href: "/hizmetler/isletme",
      },
      {
        id: "kurulum",
        label: "Investment / formation",
        title: "From Turkey to Poland — company and activity",
        bullets: [
          "Pre-decision administrative sequence and HQ document list",
          "Lawyer–notary track preparation; post-KRS NIP / REGON / VAT-UE / bank",
          "First 90 days: letter summaries and HQ–Poland bridge",
          "No incorporation or legal-outcome guarantee",
        ],
        ctaLabel: "Formation advisory",
        href: "/hizmetler/kurulum",
      },
      {
        id: "egitim",
        label: "University",
        title: "University / education correspondence",
        bullets: [
          "Upload the letter or use the consult form",
          "What is requested, deadline, missing documents",
          "Language bridge family / applicant / institution",
          "No admission or visa guarantee",
        ],
        ctaLabel: "Education guidance",
        href: "/hizmetler/egitim",
      },
      {
        id: "eslik",
        label: "On-site",
        title: "Licence, residence, offices — individuals",
        bullets: [
          "Company or individual track",
          "Licence exchange / residence card: checklist, appointment, status",
          "Remote, phone or on site; TR / PL / EN / RU / UK",
          "No card / licence / outcome guarantee",
        ],
        ctaLabel: "Accompaniment service",
        href: "/hizmetler/eslik",
      },
    ],
  },
  scope: {
    eyebrow: "Boundaries",
    title: "What we do / don’t",
    includedTitle: "We do",
    excludedTitle: "We don’t",
    included: [
      "Operators established in Turkey and Turkish or foreign-capital companies active in Poland — document and administrative process monitoring",
      "Official letter summaries; contact in TR / PL / EN / RU / UK",
      "Turkey-based operators: Poland investment, company formation and activity — administrative advisory and process initiation (company registration is out of scope)",
      "Deadline and next-step clarity",
      "Administrative guidance for education / university processes",
      "Local SMEs and logistics in Poland — activity correspondence monitoring; coordination with the lawyer partner",
      "Individuals: urząd matters, licence exchange, residence-card status — remote / phone / on site",
      "On-site accompaniment on request",
      "Document / appointment coordination (POA package)",
      "Bridge to lawyer partner and accountant",
      "Administrative support for bank-account opening (KYC list, appointment, language bridge) — no guarantee of account opening or credit approval",
      "After payment: status on the case page / Account",
    ],
    excluded: [
      "Registering the company in your name; obtaining KRS or tax decisions",
      "Legal advice and litigation",
      "University admission, scholarship or visa / residence guarantees",
      "Guaranteeing bank-account opening, PESEL, licence or medical outcomes",
      "Accounting and tax filing signatures",
      "Decision or timeline guarantees",
      "MOS / office form automation",
      "Presenting ourselves as lawyers, education agents or sworn translators",
    ],
  },
  faq: faqEn,
  lead: {
    title: "Contact",
    intro:
      "Admin tracking or a package: write to us. Unsure which package — use the form. Urgent letter: header Apply. Reply usually within one business day.",
    fullName: "Full name",
    company: "Company / title (optional)",
    employees: "Headcount (optional)",
    email: "Email",
    phone: "Phone",
    process: "Service of interest (approximate)",
    processOptions: [
      {
        value: "ticaret-masasi",
        label: "Trade advisory — Poland",
      },
      { value: "tek-yazi", label: "Single letter — ask before buying" },
      { value: "aylik-paket", label: "Monthly admin tracking (subscription) — ask first" },
      { value: "surec-yonetimi", label: "Admin execution with POA — ask first" },
      { value: "yatirimci", label: "TR operator — Poland investment / company formation" },
      { value: "isletme", label: "SME / logistics — activity papers" },
      { value: "egitim", label: "University / education process guidance" },
      { value: "eslik-firma", label: "Company — offices / accompaniment" },
      { value: "eslik-sahis", label: "Individual — licence, residence, offices" },
      { value: "diger", label: "Other" },
    ],
    privacy: "I agree to processing of my data for contact purposes.",
    submit: "Send",
    loading: "Sending…",
    success:
      "Request received. We’ll reply by email (usually within 1 business day).",
    error: "Could not send. Please try again.",
    fieldError: "Check this field.",
    modalTitle: "Contact form",
    close: "Close",
  },
  trust: {
    title: "Trust",
    badges: [
      "Not a law firm",
      "GDPR / RODO",
      "Stripe payments",
      "Case link (no email attachment)",
    ],
  },
  footer: {
    disclaimer:
      "ROUTEPOL is not a law firm or tax office. Legal advice sits with our Polish lawyer partner. No decision or timeline guarantees.",
    privacy: "Privacy",
    rights: "© ROUTEPOL. All rights reserved.",
    servicesHub: "All services",
    about: "About us",
    apply: "Apply",
    accompaniment: "On-site support",
    advisory: "Advisory",
    formation: "Investment / formation",
    business: "Business services",
    education: "Education processes",
    packages: "Packages",
    guide: "Guides",
    faq: "FAQ",
    groupServices: "Services",
    groupBuy: "Apply",
    groupSite: "Site",
  },
};
