import { faqPl } from "../faq";
import { heroDemoPl } from "../landing-hero-demo";
import type { LandingContent } from "./types";
import { landingTr } from "./tr";

export const landingPl: LandingContent = {
  ...landingTr,
  meta: {
    title: "ROUTEPOL | Trasa, która prowadzi w Polsce.",
    description:
      "ROUTEPOL — Trasa, która prowadzi w Polsce. Przedsiębiorcy z Turcji oraz firmy tureckie i zagraniczne w Polsce: pisma, dokumenty i tracking administracyjny. Streszczenie w Waszym języku. Jasny kolejny krok. Dodatkowo doradztwo handlowe.",
  },
  brand: {
    name: "ROUTEPOL",
    tagline: "Trasa, która prowadzi w Polsce.",
    secondName: "ROUTEPOL",
    secondLineHint: "Turcja · Polska",
  },
  nav: [
    { id: "hizmetler", label: "Usługi", href: "/hizmetler" },
    { id: "paketler", label: "Pakiety", href: "/hizmetler#paketler" },
    { id: "danismanlik", label: "Doradztwo", href: "/danismanlik" },
    { id: "hakkimizda", label: "O nas", href: "/hakkimizda" },
    { id: "rehber", label: "Przewodnik", href: "/rehber" },
    { id: "sss", label: "FAQ", href: "#sss" },
    { id: "iletisim", label: "Kontakt", href: "#iletisim" },
  ],
  headerCta: "Złóż wniosek",
  accountLink: "Logowanie",
  hero: {
    eyebrow: "Turcja · Polska",
    title: "Sprawy administracyjne w PL — w jednym miejscu.",
    subtitle:
      "Streszczamy pisma urzędowe w Waszym języku. Termin i kolejny krok pozostają jasne. Tracking dokumentów u nas. Decyzja u Państwa.",
    valueLine:
      "Nie jesteśmy kancelarią. Wpis i reprezentacja u adwokata-partnera. Doradztwo handlowe to osobna linia usług.",
    ctaPrimary: "Zobacz pakiety",
    ctaPrimaryHref: "/hizmetler#paketler",
    ctaSecondary: "Doradztwo handlowe",
    ctaSecondaryHref: "/danismanlik",
    demo: heroDemoPl,
  },
  bridge: {
    eyebrow: "Jak to działa",
    title: "Instytucja pisze. My śledzimy. Państwo decydujecie.",
    intro:
      "Teczka administracyjna w PL zbiera się w jednym miejscu. Język, termin i krok nie giną.",
    lanes: [
      {
        id: "kurum",
        label: "Instytucja",
        body: "Urząd, ZUS, urząd skarbowy lub bank wysyła oficjalne wezwanie — zwykle po polsku.",
      },
      {
        id: "pol-turk",
        label: "ROUTEPOL",
        body: "Streszczamy pismo w Waszym języku. Ujasniamy termin i kolejny krok. Prowadzimy teczkę.",
      },
      {
        id: "siz",
        label: "Państwo",
        body: "Zatwierdzacie zakres. Dostarczacie dokumenty. Decyzja i podpis zostają u Państwa lub u uprawnionego partnera.",
      },
    ],
    lawyerNote:
      "Porada prawna, reprezentacja i wpis pozostają u adwokata-partnera. ROUTEPOL w tę linię nie wchodzi.",
    serviceLine: {
      title: "Doradztwo handlowe",
      body: "Widoczność rynku, mapa kontrahentów, spotkania i zestawienie ofert. Osobno od trackingu administracyjnego.",
      ctaLabel: "Zobacz",
      href: "/danismanlik",
    },
  },
  audiences: {
    eyebrow: "Dla kogo",
    title: "Linie usług",
    intro:
      "Inwestycja korporacyjna, lokalna działalność, administracja edukacyjna i sprawy urzędowe osób — ten sam standard operacyjny: zakres na piśmie, most językowy, tracking, koordynacja z partnerem uprawnionym.",
    items: [
      {
        id: "yatirimci",
        icon: "Building2",
        title: "Inwestycja i założenie spółki z Turcji",
        body: "Podmioty z Turcji: inwestycja w Polsce, sp. z o.o. / oddział / działalność oraz pierwszy rok administracji. Mapa procesu, przygotowanie teczki i inicjacja ścieżki adwokat–notariusz–KRS. Decyzja wpisu pozostaje u urzędu i adwokata-partnera.",
        points: [
          "Przed decyzją: obciążenie administracyjne struktur, kolejność, checklist centrali",
          "Okres założenia: wizyta u adwokata-partnera, braki dokumentów, po KRS: NIP/REGON/VAT-UE/bank",
          "Działalność: streszczenia pism, most centrala–Polska, prowadzenie z POA",
        ],
        ctaLabel: "Doradztwo inwestycyjne i założenie",
        href: "/hizmetler/kurulum",
      },
      {
        id: "isletme",
        icon: "Store",
        title: "Tureckie MŚP / JDG w PL",
        body: "Gastronomia, logistyka / transport, hurt, budowa — US/ZUS/KRS i dokumenty działalności; most do adwokata-partnera.",
        points: [
          "Pismo: żądanie, termin",
          "Logistyka / teren — pisma i wizyty",
          "Notatka do księgowego; prawo u adwokata-partnera (nie my doradzamy)",
        ],
        ctaLabel: "Usługi dla firm",
        href: "/hizmetler/isletme",
      },
      {
        id: "egitim",
        icon: "GraduationCap",
        title: "Uczelnia i procesy edukacyjne",
        body: "Guidance administracyjny przy rekrutacji i korespondencji uczelni. Most językowy rodzina–instytucja. Bez gwarancji przyjęcia.",
        points: [
          "Checklist dokumentów",
          "Streszczenie pism uczelni / akademika",
          "Dla kandydata, rodziny lub jednostki edukacyjnej",
        ],
        ctaLabel: "Guidance edukacyjny",
        href: "/hizmetler/egitim",
      },
      {
        id: "sahis",
        icon: "User",
        title: "Turcy w PL — osoby prywatne",
        body: "Urzędy: tracking dokumentów, informacja zdalna / telefoniczna, karta pobytu i prawo jazdy. Bez gwarancji decyzji.",
        points: [
          "Wymiana prawa jazdy na polskie — kroki, dokumenty, wizyta (decyzja urzędu)",
          "Karta pobytu: streszczenie pism, braki, status",
          "Tłumaczenia: most językowy; przysięgły — kierujemy, nie wykonujemy",
        ],
        ctaLabel: "Wsparcie dla osób",
        href: "/hizmetler/eslik#sahis",
      },
    ],
  },
  fieldSupport: {
    eyebrow: "Towarzyszenie na miejscu",
    title: "Wsparcie urzędowe dla firm i osób",
    intro:
      "Obok pakietów: urzędy, bank, PESEL, prawo jazdy. Pakiety pisemne i towarzyszenie na miejscu — formularz kontaktowy. Języki: TR / PL / EN / RU / UK.",
    items: [
      {
        id: "eslik-firma",
        icon: "Building2",
        title: "Firma / spółka",
        body: "MŚP i spółki z inwestycji TR: KYC, US/ZUS/KRS, dokumenty logistyki, strona pracodawcy.",
        points: [
          "Konto firmowe / KYC i wizyty",
          "Logistyka — pisma i terminy",
          "Opcjonalnie towarzyszenie w urzędzie / banku",
        ],
        ctaLabel: "Towarzyszenie — firma",
        href: "/hizmetler/eslik#firma",
      },
      {
        id: "eslik-sahis",
        icon: "User",
        title: "Osoba prywatna",
        body: "Turcy w PL: urząd, PESEL, wymiana prawa jazdy, karta pobytu — zdalnie, telefon lub na miejscu.",
        points: [
          "Prawo jazdy / karta pobytu: checklist, wizyta, status (decyzja urzędu)",
          "Informacja telefoniczna i zdalna",
          "Opcjonalnie towarzyszenie; TR / PL / EN / RU / UK",
        ],
        ctaLabel: "Towarzyszenie — osoba",
        href: "/hizmetler/eslik#sahis",
      },
    ],
    disclaimer:
      "Bez gwarancji konta, PESEL, prawa jazdy ani orzeczenia. Prawo u adwokata-partnera.",
    hubCta: "Strona towarzyszenia",
    hubHref: "/hizmetler/eslik",
  },
  categories: {
    eyebrow: "Obszary",
    title: "Korporacyjne obszary usług",
    intro:
      "Trzy pakiety płatne oraz doradztwo inwestycyjne/założenie, biurko firmy, administracja edukacyjna i linia urzędowa osób. Całość to doradztwo administracyjne — bez porad prawnych, wpisu KRS i podpisu podatkowego.",
    items: [
      {
        id: "yazi-ozeti",
        icon: "FileText",
        title: "Streszczenie pisma",
        body: "Jedno pismo: wyjaśnienie PL / EN / TR, termin, kto co robi.",
        packageSlug: "tek-yazi",
        href: "/hizmetler/tek-yazi",
        ctaLabel: "Jedno pismo",
        badge: "Pakiet",
      },
      {
        id: "evrak-takip",
        icon: "Mail",
        title: "Tracking administracyjny",
        body: "Pisma w miesiącu; abonament Stripe (odnowienie automatyczne). Opłata okresowa także bez pism. Status na stronie sprawy / Koncie; overage jasny.",
        packageSlug: "aylik-paket",
        href: "/hizmetler/aylik-paket",
        ctaLabel: "Abonament miesięczny",
        badge: "Pakiet",
      },
      {
        id: "vekaletli",
        icon: "FileSignature",
        title: "Prowadzenie z pełnomocnictwem",
        body: "Koordynacja dokumentów i wizyt z pełnomocnictwem notarialnym. Rejestracja i okres intensywny.",
        packageSlug: "surec-yonetimi",
        href: "/hizmetler/surec-yonetimi",
        ctaLabel: "Pakiet z POA",
        badge: "Pakiet",
      },
      {
        id: "surec-yonlendirme",
        icon: "Map",
        title: "Inwestycja, założenie i doradztwo procesowe",
        body: "Przedsiębiorcy z Turcji: założenie spółki i uruchomienie działalności w PL — kolejność dokumentów, przygotowanie ścieżki adwokat–notariusz, administracja po wpisie. Nie wpisujemy spółki za Państwa.",
        href: "/hizmetler/kurulum",
        ctaLabel: "Doradztwo założenia",
        badge: "Konsultacja",
      },
      {
        id: "sahis-idari",
        icon: "User",
        title: "Osoby — urząd, prawo jazdy, pobyt",
        body: "Turcy w PL: tracking dokumentów, wymiana prawa jazdy, karta pobytu. Bez gwarancji decyzji.",
        href: "/hizmetler/eslik#sahis",
        ctaLabel: "Linia osób",
        badge: "Konsultacja",
      },
      {
        id: "egitim-yonlendirme",
        icon: "GraduationCap",
        title: "Guidance uczelniany / edukacyjny",
        body: "Porządek dokumentacji i mapa procesu przy ścieżkach edukacyjnych.",
        href: "/hizmetler/egitim",
        ctaLabel: "Strona edukacji",
        badge: "Konsultacja",
      },
    ],
  },
  packages: {
    eyebrow: "Pakiety",
    title: "Pakiety do zamówienia",
    intro:
      "Cztery pakiety: Jedno pismo, Opieka miesięczna (abonament), Prowadzenie z POA (abonament), Towarzyszenie na miejscu. Pakiety miesięczne odnawiają się kartą automatycznie. Po płatności otwiera się sprawa.",
    applyLabel: "Złóż wniosek",
    detailLabel: "Szczegóły",
    talkLabel: "Najpierw napiszcie — pytanie bez wyboru pakietu",
    talkHref: "#iletisim",
    featuredStory: {
      title: "W ciągu miesiąca",
      steps: [
        "Pismo streszczane w Waszym języku",
        "Termin i kolejny krok jasne",
        "Śledzenie na stronie sprawy",
      ],
    },
  },
  process: {
    eyebrow: "Jak działa",
    title: "Dwie ścieżki — pakiet lub towarzyszenie",
    intro:
      "Macie pismo — pakiet pisemny. Towarzyszenie na miejscu (urząd / bank / biuro) to osobny pakiet na stronie — miasto obowiązkowe; dojazd poza miastem osobno. Konsultacja telefoniczna nie jest obecnie dostępna; ogólne pytania — formularz kontaktowy.",
    paidPathTitle: "Cztery kroki w pakietach płatnych",
    steps: [
      {
        title: "Wybierzcie pakiet",
        body: "Przy pismach — PDF / zdjęcie. Przy towarzyszeniu — miasto i krótki briefing.",
      },
      {
        title: "Płatność",
        body: "Stripe. Link do sprawy na e-mail.",
      },
      {
        title: "Wyjaśnienie + tracking",
        body: "Czego żądają, termin, kolejny krok — w Waszym języku.",
      },
      {
        title: "Wynik",
        body: "Pobieracie ze strony sprawy. Bez załącznika w mailu.",
      },
    ],
    consultPathTitle: "Towarzyszenie na miejscu (urząd / bank)",
    consultPathBody:
      "Pakiet pół dnia: 450 zł, 1 urząd / 1 wizyta. Stawka bazowa na całą Polskę; dojazd poza miastem osobno. Bez gwarancji decyzji. Intensywny okres administracyjny — osobny pakiet z POA.",
    consultSteps: [
      {
        title: "Wybierzcie pakiet",
        body: "We wniosku: Towarzyszenie na miejscu; miasto i cel wizyty.",
      },
      {
        title: "Płatność",
        body: "450 zł pół dnia — Stripe. Operator potwierdza termin.",
      },
      {
        title: "Dzień wizyty",
        body: "Most językowy w urzędzie / banku / biurze; to nie reprezentacja prawna.",
      },
      {
        title: "Notatka",
        body: "Co się stało, co dalej — na stronie sprawy.",
      },
    ],
    ctaPackage: "Do pakietów",
    ctaConsult: "Wniosek — towarzyszenie",
  },
  cases: {
    eyebrow: "Przykłady",
    title: "Typowe sprawy",
    intro: "Bez gwarancji decyzji urzędu ani wyniku prawnego.",
    tabs: [
      {
        id: "us-zus",
        label: "US / ZUS",
        title: "Pismo US lub ZUS",
        bullets: [
          "Wgrajcie pismo (jedno pismo lub pakiet miesięczny)",
          "Streszczenie: żądanie, termin, załączniki",
          "Notatka do księgowego",
          "W razie potrzeby most do adwokata",
        ],
        ctaLabel: "Pakiety",
        href: "/hizmetler#paketler",
      },
      {
        id: "krs",
        label: "KRS",
        title: "Zmiany KRS / spółki",
        bullets: [
          "Kolejność dokumentów",
          "Koordynacja wizyt (pakiet z POA)",
          "Status w Waszym języku",
          "Decyzja u adwokata / uprawnionego",
        ],
        ctaLabel: "Pakiet z POA",
        href: "/hizmetler/surec-yonetimi",
      },
      {
        id: "calisan",
        label: "Pobyt pracownika",
        title: "Strona pracodawcy",
        bullets: [
          "Checklist pracodawcy (jedno pismo / opieka miesięczna)",
          "Kontrola braków",
          "Przewodnik: pismo, pakiety, założenie, osoba, MOS",
          "Reprezentacja u adwokata",
        ],
        ctaLabel: "Usługi dla firm",
        href: "/hizmetler/isletme",
      },
      {
        id: "kurulum",
        label: "Inwestycja / założenie",
        title: "Z Turcji do Polski — spółka i działalność",
        bullets: [
          "Przed decyzją: kolejność administracyjna i lista dokumentów centrali",
          "Przygotowanie ścieżki adwokat–notariusz; po KRS: NIP / REGON / VAT-UE / bank",
          "Pierwsze 90 dni: streszczenia pism i most centrala–Polska",
          "Bez gwarancji wpisu ani wyniku prawnego",
        ],
        ctaLabel: "Doradztwo założenia",
        href: "/hizmetler/kurulum",
      },
      {
        id: "egitim",
        label: "Uczelnia",
        title: "Korespondencja uczelniana / edukacyjna",
        bullets: [
          "Wgrajcie pismo lub formularz konsultacji",
          "Żądanie, termin, braki dokumentów",
          "Most językowy rodzina / kandydat / instytucja",
          "Bez gwarancji przyjęcia ani wizy",
        ],
        ctaLabel: "Guidance edukacyjny",
        href: "/hizmetler/egitim",
      },
      {
        id: "eslik",
        label: "Towarzyszenie",
        title: "Prawo jazdy, pobyt, urząd — osoby",
        bullets: [
          "Linia firma lub osoba",
          "Wymiana prawa jazdy / karta pobytu: checklist, wizyta, status",
          "Zdalnie, telefon lub na miejscu; TR / PL / EN / RU / UK",
          "Bez gwarancji karty / prawa jazdy / decyzji",
        ],
        ctaLabel: "Towarzyszenie",
        href: "/hizmetler/eslik",
      },
    ],
  },
  scope: {
    eyebrow: "Granice",
    title: "Co robimy / czego nie",
    includedTitle: "Robimy",
    excludedTitle: "Nie robimy",
    included: [
      "Przedsiębiorcy z siedzibą w Turcji oraz firmy tureckie i zagraniczne działające w Polsce — monitoring pism i spraw administracyjnych",
      "Streszczenie pism urzędowych; kontakt TR / PL / EN / RU / UK",
      "Przedsiębiorcy z TR: inwestycja, założenie spółki i działalność w PL — doradztwo administracyjne i inicjacja procesu (wpis KRS poza naszym zakresem)",
      "Utrzymanie terminu i kolejnego kroku",
      "Guidance administracyjny przy procesie edukacyjnym / uczelni",
      "Lokalne MŚP i logistyka w PL — monitoring pism działalności; koordynacja z adwokatem-partnerem",
      "Osoby: urząd, wymiana prawa jazdy, karta pobytu — zdalnie / telefon / na miejscu",
      "Towarzyszenie na życzenie",
      "Koordynacja dokumentów / wizyt (z POA)",
      "Most do adwokata i księgowego",
      "Wsparcie administracyjne przy otwarciu konta bankowego (lista KYC, wizyta, most językowy) — bez gwarancji otwarcia konta lub kredytu",
      "Po płatności status na stronie sprawy / Koncie",
    ],
    excluded: [
      "Wpis spółki za Państwa; decyzja KRS / podatkowa",
      "Porady prawne i procesy sądowe",
      "Gwarancja przyjęcia na uczelnię, stypendium lub wizy / pobytu",
      "Gwarancja otwarcia konta bankowego, PESEL, prawa jazdy lub orzeczenia",
      "Księgowość i podpis podatkowy",
      "Gwarancja decyzji / terminu",
      "Automatyzacja formularzy MOS / urząd",
      "Podawanie się za adwokata / agencję edukacyjną / tłumacza przysięgłego",
    ],
  },
  faq: faqPl,
  lead: {
    title: "Kontakt",
    intro:
      "Tracking administracyjny lub pakiet: napiszcie. Nie wiecie, który pakiet — wypełnijcie formularz. Pilne pismo: menu «Złóż wniosek». Odpowiedź zwykle w jeden dzień roboczy.",
    fullName: "Imię i nazwisko",
    company: "Firma / tytuł (opcjonalnie)",
    employees: "Liczba pracowników (opcjonalnie)",
    email: "E-mail",
    phone: "Telefon",
    process: "Usługa (orientacyjnie)",
    processOptions: [
      {
        value: "ticaret-masasi",
        label: "Doradztwo handlowe — Polska",
      },
      { value: "tek-yazi", label: "Jedno pismo — pytanie przed zakupem" },
      { value: "aylik-paket", label: "Opieka miesięczna (abonament) — najpierw pytanie" },
      { value: "surec-yonetimi", label: "Prowadzenie z pełnomocnictwem — najpierw pytanie" },
      { value: "yatirimci", label: "Przedsiębiorca TR — inwestycja / założenie spółki w PL" },
      { value: "isletme", label: "MŚP / logistyka — dokumenty działalności" },
      { value: "egitim", label: "Uczelnia / guidance edukacyjny" },
      { value: "eslik-firma", label: "Firma — urząd / towarzyszenie" },
      { value: "eslik-sahis", label: "Osoba — prawo jazdy, pobyt, urząd" },
      { value: "diger", label: "Inne" },
    ],
    privacy: "Akceptuję przetwarzanie danych w celu kontaktu.",
    submit: "Wyślij",
    loading: "Wysyłanie…",
    success:
      "Otrzymaliśmy zgłoszenie. Odezwiemy się e-mailem (zwykle 1 dzień roboczy).",
    error: "Nie udało się. Spróbuj ponownie.",
    fieldError: "Sprawdź to pole.",
    modalTitle: "Formularz kontaktowy",
    close: "Zamknij",
  },
  trust: {
    title: "Zaufanie",
    badges: [
      "Nie jesteśmy kancelarią",
      "RODO",
      "Płatność Stripe",
      "Link do sprawy (bez załącznika)",
    ],
  },
  footer: {
    disclaimer:
      "ROUTEPOL nie świadczy usług adwokackich ani księgowych. Porady prawne u polskiego partnera. Bez gwarancji decyzji.",
    privacy: "Prywatność",
    rights: "© ROUTEPOL. Wszelkie prawa zastrzeżone.",
    servicesHub: "Wszystkie usługi",
    about: "O nas",
    apply: "Złóż wniosek",
    accompaniment: "Towarzyszenie",
    advisory: "Doradztwo",
    formation: "Inwestycja / założenie",
    business: "Usługi dla firm",
    education: "Procesy edukacyjne",
    packages: "Pakiety",
    guide: "Przewodnik",
    faq: "FAQ",
    groupServices: "Usługi",
    groupBuy: "Wniosek",
    groupSite: "Serwis",
  },
};
