services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: polturk
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: polturk
    ports:
      - "5432:5432"
    volumes:
      - polturk_pg:/var/lib/postgresql/data

volumes:
  polturk_pg:
