import { faqTr } from "../faq";
import { heroDemoTr } from "../landing-hero-demo";
import type { LandingContent } from "./types";

export const landingTr: LandingContent = {
  meta: {
    title: "ROUTEPOL | Polonya’da yol gösteren rota.",
    description:
      "ROUTEPOL — Polonya’da yol gösteren rota. Türkiye’de yerleşik işletmeciler ile Polonya’da faaliyet gösteren Türk ve yabancı sermayeli şirketler için resmi yazı, evrak ve idari süreç takibi. Dilinizde özet. Net adım. Ayrıca ticaret danışmanlığı.",
  },
  brand: {
    name: "ROUTEPOL",
    tagline: "Polonya’da yol gösteren rota.",
    secondName: "ROUTEPOL",
    secondLineHint: "Türkiye · Polonya",
  },
  nav: [
    {
      id: "hizmetler",
      label: "Hizmetler",
      href: "/hizmetler",
      children: [
        {
          id: "hub",
          label: "Tüm hizmetler",
          href: "/hizmetler",
          description: "Hub — paketler ve hatlar",
        },
        {
          id: "paketler-alt",
          label: "Paketler",
          href: "/hizmetler#paketler",
          description: "Tek yazı, aylık, vekaletli, eşlik",
        },
        {
          id: "eslik",
          label: "Yerinde eşlik",
          href: "/hizmetler/eslik",
          description: "Ofis / banka / urząd dil köprüsü",
        },
        {
          id: "danismanlik",
          label: "Ticaret danışmanlığı",
          href: "/danismanlik",
          description: "Ayrı hat — idari takipten ayrı",
        },
        {
          id: "kurulum",
          label: "Yatırım / kuruluş",
          href: "/hizmetler/kurulum",
          description: "TR işletmeci — Polonya süreçleri",
        },
        {
          id: "egitim",
          label: "Eğitim süreçleri",
          href: "/hizmetler/egitim",
          description: "Üniversite / idari yönlendirme",
        },
      ],
    },
    { id: "paketler", label: "Paketler", href: "/hizmetler#paketler" },
    {
      id: "sirket",
      label: "Şirket",
      href: "/hakkimizda",
      children: [
        {
          id: "hakkimizda",
          label: "Hakkımızda",
          href: "/hakkimizda",
          description: "Kimiz, ne yapıyoruz",
        },
        {
          id: "rehber",
          label: "Rehber",
          href: "/rehber",
          description: "Süreç ve kapsam özeti",
        },
        {
          id: "sss",
          label: "SSS",
          href: "#sss",
          description: "Sık sorulanlar",
        },
      ],
    },
    { id: "iletisim", label: "İletişim", href: "#iletisim" },
  ],
  headerCta: "Başvur",
  accountLink: "Giriş",
  hero: {
    eyebrow: "Türkiye · Polonya",
    title: "Polonya’daki idari işleriniz, tek noktada.",
    subtitle:
      "Resmi yazıları dilinizde özetler; son tarihi ve sıradaki adımı net tutarız. Evrak ve süreç takibi bizde. Karar sizde.",
    valueLine:
      "Avukat değiliz. Tescil ve hukuki temsil avukat ortağındadır. Ticaret danışmanlığı ayrı bir hizmet hattıdır.",
    ctaPrimary: "Paketleri inceleyin",
    ctaPrimaryHref: "/hizmetler#paketler",
    ctaSecondary: "Ticaret danışmanlığı",
    ctaSecondaryHref: "/danismanlik",
    demo: heroDemoTr,
  },
  bridge: {
    eyebrow: "Nasıl çalışır",
    title: "Kurum yazar. Biz takip ederiz. Siz karar verirsiniz.",
    intro:
      "Polonya’daki idari dosya tek yerde toplanır. Dil, tarih ve adım kaybolmaz.",
    lanes: [
      {
        id: "kurum",
        label: "Kurum",
        body: "Urząd, ZUS, vergi dairesi veya banka resmi talep gönderir — çoğu zaman Lehçe.",
      },
      {
        id: "pol-turk",
        label: "ROUTEPOL",
        body: "Yazıyı dilinizde özetleriz. Son tarihi ve sıradaki adımı netleştiririz. Dosyayı takip ederiz.",
      },
      {
        id: "siz",
        label: "Siz",
        body: "Kapsamı onaylarsınız. Belgeyi sağlarsınız. Karar ve imza sizde veya yetkili ortağınızda kalır.",
      },
    ],
    lawyerNote:
      "Hukuki tavsiye, temsil ve tescil avukat ortağındadır. ROUTEPOL bu hatta girmez.",
    serviceLine: {
      title: "Ticaret danışmanlığı",
      body: "Pazar görünürlüğü, karşı taraf haritası, görüşme ve teklif derlemesi. İdari takipten ayrı sunulur.",
      ctaLabel: "İnceleyin",
      href: "/danismanlik",
    },
  },
  audiences: {
    eyebrow: "Kim için",
    title: "Hizmet hatları",
    intro:
      "Kurumsal yatırım, yereldeki işletme, eğitim idaresi ve şahıs urząd işleri aynı operasyon standardında yürütülür: yazılı kapsam, dil köprüsü, takip, yetkili ortağa koordinasyon.",
    items: [
      {
        id: "yatirimci",
        icon: "Building2",
        title: "Türkiye’den yatırım ve şirket kuruluşu",
        body: "Türkiye merkezli işletmecilerin Polonya’daki yatırım, sp. z o.o. / şube / faaliyet açılışı ve ilk yıl idaresinde danışmanlık. Süreç haritası, evrak hazırlığı ve avukat–noter–KRS akışına ön ayak oluruz; tescil kararı mercide ve avukat ortağındadır.",
        points: [
          "Karar öncesi: yapı seçeneklerinin idari yükü, sıra, merkez ofis checklist’i",
          "Kuruluş dönemi: avukat ortağı randevusu, eksik evrak, KRS sonrası NIP/REGON/VAT-UE/banka takibi",
          "Faaliyet: kurum yazısı özeti, merkez–Polonya köprüsü, vekaletli idari yürütme",
        ],
        ctaLabel: "Yatırım ve kuruluş danışmanlığı",
        href: "/hizmetler/kurulum",
      },
      {
        id: "isletme",
        icon: "Store",
        title: "Polonya’daki işletmeler (KOBİ / JDG)",
        body: "Yerelde faaliyet gösteren Türk işletmeleri: gastronomi, lojistik, toptan, inşaat. Kurum yazışması, faaliyet evrakı ve muhasebe–avukat koordinasyonu.",
        points: [
          "US / ZUS / KRS ve belediye yazılarının özeti ve son tarih takibi",
          "Lojistik ve saha faaliyetinde randevu / evrak koordinasyonu",
          "Muhasebeye operasyon notu; hukuki dosyada avukat ortağına iletim",
        ],
        ctaLabel: "Kurumsal işletme masası",
        href: "/hizmetler/isletme",
      },
      {
        id: "egitim",
        icon: "GraduationCap",
        title: "Yükseköğretim ve eğitim idaresi",
        body: "Üniversite ve eğitim kurumlarına bağlı idari süreç: evrak düzeni, kurum yazısı özeti, aile–aday–kurum dil köprüsü. Kabul veya vize taahhüdü yoktur.",
        points: [
          "Başvuru ve kayıt evrak listesi",
          "Kurum ve yurt yazışmalarının dilde açıklaması",
          "Aday, veli veya eğitim birimi için aynı raporlama standardı",
        ],
        ctaLabel: "Eğitim idari yönlendirme",
        href: "/hizmetler/egitim",
      },
      {
        id: "sahis",
        icon: "User",
        title: "Şahıs — Polonya’daki Türk vatandaşları",
        body: "Devlet daireleri, oturum kartı, ehliyet ve evrak takibi. Uzaktan, telefonla veya yerinde eşlik. Kurum kararı taahhüt edilmez.",
        points: [
          "Yabancı ehliyetin Polonya ehliyetine çevrilmesi: adımlar, evrak, randevu",
          "Oturum kartı / pobyt: yazı özeti, eksik belge, durum raporu",
          "Çeviri ihtiyacı: dil köprüsü ve yeminli tercümana yönlendirme",
        ],
        ctaLabel: "Şahıs idari hizmetler",
        href: "/hizmetler/eslik#sahis",
      },
    ],
  },
  fieldSupport: {
    eyebrow: "Yerinde eşlik",
    title: "Firma ve şahıs — kurumlar arası idare",
    intro:
      "Yazı paketlerinin yanında: urząd, banka, PESEL, ehliyet, oturum. Yazılı paketler veya yerinde eşlik için iletişim formu. Diller: TR / PL / EN / RU / UK.",
    items: [
      {
        id: "eslik-firma",
        icon: "Building2",
        title: "Firma / şirket",
        body: "KOBİ ve yatırım kuruluşu işyeri: banka KYC, US/ZUS/KRS, lojistik / faaliyet evrakı, çalışan dosyasında işveren tarafı.",
        points: [
          "Şirket hesabı / KYC ve kurum ziyareti koordinasyonu",
          "Lojistik ve saha faaliyetinde yazı / randevu masası",
          "İstenirse ofiste / bankada / urząd’da fiziksel eşlik",
        ],
        ctaLabel: "Firma eşlik detayı",
        href: "/hizmetler/eslik#firma",
      },
      {
        id: "eslik-sahis",
        icon: "User",
        title: "Şahıs / bireysel",
        body: "Polonya’daki Türkler: urząd, PESEL, ehliyet çevirisi, oturum kartı, sağlık raporu, kişisel banka — uzaktan, telefon veya yerinde.",
        points: [
          "Ehliyet / oturum kartı: checklist, randevu, durum takibi (karar mercidedir)",
          "Telefon ve uzaktan bilgi: ne isteniyor, sıradaki adım",
          "İstenirse birebir eşlik; TR / PL / EN / RU / UK dil köprüsü",
        ],
        ctaLabel: "Şahıs eşlik detayı",
        href: "/hizmetler/eslik#sahis",
      },
    ],
    disclaimer:
      "Hesap açılışı, PESEL, ehliyet veya sağlık sonucu taahhüt edilmez. Hukuki temsil avukat ortağındadır.",
    hubCta: "Yerinde eşlik sayfası",
    hubHref: "/hizmetler/eslik",
  },
  categories: {
    eyebrow: "Hizmet alanları",
    title: "Kurumsal hizmet alanları",
    intro:
      "Ücretli paketler (yazı + yerinde eşlik) ile yatırım/kuruluş danışmanlığı, işletme masası, eğitim idaresi ve şahıs urząd hattı. Tümü idari danışmanlıktır; hukuki tavsiye, tescil ve vergi imzası dahil değildir.",
    items: [
      {
        id: "yazi-ozeti",
        icon: "FileText",
        title: "Resmi yazı özeti",
        body: "Tek kurum yazısı: dilde açıklama (iletişim TR / PL / EN / RU / UK), son tarih, kim ne yapar.",
        packageSlug: "tek-yazi",
        href: "/hizmetler/tek-yazi",
        ctaLabel: "Tek yazı",
        badge: "Paket",
      },
      {
        id: "evrak-takip",
        icon: "Mail",
        title: "Evrak ve idari takip",
        body: "Ay boyunca gelen yazılar; Stripe abonelik (otomatik yenileme). Dönem ücreti yazı gelmese de alınır. Dosya sayfası / İş masası; aşım net.",
        packageSlug: "aylik-paket",
        href: "/hizmetler/aylik-paket",
        ctaLabel: "Aylık abonelik",
        badge: "Paket",
      },
      {
        id: "vekaletli",
        icon: "FileSignature",
        title: "Vekaletli idari yürütme",
        body: "Noter idari vekaletiyle evrak ve randevu koordinasyonu; avukat ücreti ayrı. Kuruluş ve yoğun dönem için.",
        packageSlug: "surec-yonetimi",
        href: "/hizmetler/surec-yonetimi",
        ctaLabel: "Vekaletli paket",
        badge: "Paket",
      },
      {
        id: "surec-yonlendirme",
        icon: "Map",
        title: "Yatırım, kuruluş ve süreç danışmanlığı",
        body: "Türkiye’deki işletmecilerin Polonya’daki şirket kuruluşu ve faaliyet açılışı: evrak sırası, avukat–noter akışına hazırlık, kayıt sonrası idare. Tescili sizin adınıza yapmayız.",
        href: "/hizmetler/kurulum",
        ctaLabel: "Kuruluş danışmanlığı",
        badge: "Görüşme",
      },
      {
        id: "sahis-idari",
        icon: "User",
        title: "Şahıs — urząd, ehliyet, oturum",
        body: "Polonya’daki Türkler: evrak takibi, ehliyet çevirisi ve oturum kartı süreci. Onay garantisi yok.",
        href: "/hizmetler/eslik#sahis",
        ctaLabel: "Şahıs hattı",
        badge: "Görüşme",
      },
      {
        id: "egitim-yonlendirme",
        icon: "GraduationCap",
        title: "Üniversite / eğitim yönlendirme",
        body: "Eğitim sürecinde dokümantasyon düzeni, süreç haritası ve kurum yazı takibi — kurumsal bilgilendirme.",
        href: "/hizmetler/egitim",
        ctaLabel: "Eğitim sayfası",
        badge: "Görüşme",
      },
    ],
  },
  packages: {
    eyebrow: "Paketler ve fiyatlar",
    title: "İhtiyacınıza uyan paket",
    intro:
      "Dört paket: Tek yazı, Aylık takip (abonelik), Vekaletli yürütme (abonelik), Yerinde eşlik. Aylık paketler karttan otomatik yenilenir. Ödeme sonrası dosya açılır.",
    applyLabel: "Başvur",
    detailLabel: "Detay",
    talkLabel: "Önce yazın — paket seçmeden soru sorun",
    talkHref: "#iletisim",
    featuredStory: {
      title: "Ay boyunca",
      steps: [
        "Gelen resmi yazı dilinizde özetlenir",
        "Son tarih ve sıradaki adım netleşir",
        "Dosya sayfanızdan takip edilir",
      ],
    },
  },
  process: {
    eyebrow: "Nasıl işler",
    title: "İki yol — paket veya yerinde eşlik",
    intro:
      "Elinizde kurum yazısı varsa yazı paketini alın. Yerinde eşlik (ofis / banka / urząd) ayrı paket olarak siteden alınır — şehir zorunlu; şehir dışı ulaşım ayrıca. Telefon görüşmesi şu an sunulmuyor; genel soru için iletişim formu.",
    paidPathTitle: "Ücretli paketlerde dört adım",
    steps: [
      {
        title: "Paketi seçin",
        body: "Yazı paketlerinde resmi yazıyı (PDF / fotoğraf) ekleyin. Yerinde eşlikte şehir ve kısa brifing yeter.",
      },
      {
        title: "Ödeme",
        body: "Stripe ile ödeme. Sonra özel dosya linkiniz e-postanıza gelir.",
      },
      {
        title: "Açıklama + takip",
        body: "Ne istendi, son tarih, sıradaki adım — dilinizde. Gerekirse avukat ortağına köprü.",
      },
      {
        title: "Sonuç",
        body: "Hazır özeti dosya sayfanızdan indirirsiniz. Mail eki yok; link aynı kalır.",
      },
    ],
    consultPathTitle: "Yerinde eşlik (ofis / banka / urząd)",
    consultPathBody:
      "Yarı gün paket: 450 zł, 1 kurum / 1 randevu. Polonya geneli taban ücret; şehir dışı ulaşım ayrıca netleştirilir. Onay veya süre garantisi yoktur. Yoğun idari dönem için vekaletli paket ayrıdır.",
    consultSteps: [
      {
        title: "Paketi seçin",
        body: "Başvuruda Yerinde eşlik; şehir ve ziyaret konusu yazın.",
      },
      {
        title: "Ödeme",
        body: "450 zł yarı gün — Stripe. Operatör randevuyu teyit eder.",
      },
      {
        title: "Eşlik günü",
        body: "Ofis / banka / urząd’da dil köprüsü; hukuki temsil değildir.",
      },
      {
        title: "Durum notu",
        body: "Ne oldu, sıradaki adım — dosya sayfanızda.",
      },
    ],
    ctaPackage: "Paketlere git",
    ctaConsult: "Yerinde eşlik başvurusu",
  },
  cases: {
    eyebrow: "Örnek durumlar",
    title: "Sık gelen işler",
    intro: "Sonuç veya hukuki karar garantisi değildir.",
    tabs: [
      {
        id: "us-zus",
        label: "US / ZUS yazısı",
        title: "Vergi veya ZUS yazısı geldi",
        bullets: [
          "Yazıyı yükleyin (tek yazı veya aylık paket)",
          "Özet: ne isteniyor, son tarih, ekler",
          "Muhasebeciye iletilecek net not",
          "Hukuk gerekirse avukat ortağına yönlendirme",
        ],
        ctaLabel: "Tek yazı / aylık paket",
        href: "/hizmetler#paketler",
      },
      {
        id: "krs",
        label: "KRS / şirket",
        title: "KRS veya şirket değişikliği",
        bullets: [
          "Adres, yönetim, sermaye — evrak sırası bilgilendirmesi",
          "Noter / kurum randevu koordinasyonu (vekaletli pakette)",
          "Durum takibi dilinizde",
          "Karar ve imza avukat / yetkilide",
        ],
        ctaLabel: "Vekaletli paket",
        href: "/hizmetler/surec-yonetimi",
      },
      {
        id: "calisan",
        label: "Çalışan oturum",
        title: "İşveren tarafı — oturum dosyası",
        bullets: [
          "İşveren tarafı evrak checklist’i (tek yazı veya aylık takip)",
          "Eksik evrak kontrolü",
          "Rehber: kurum yazısı, paket seçimi, kuruluş, şahıs, MOS",
          "Hukuki temsil avukat ortağında",
        ],
        ctaLabel: "İşletme hizmetleri",
        href: "/hizmetler/isletme",
      },
      {
        id: "kurulum",
        label: "Yatırım / kuruluş",
        title: "Türkiye’den Polonya’ya şirket ve faaliyet",
        bullets: [
          "Karar öncesi idari sıra ve merkez ofis evrak listesi",
          "Avukat ortağı ve noter akışına hazırlık; KRS sonrası NIP / REGON / VAT-UE / banka takibi",
          "İlk 90 gün kurum yazılarının özeti ve merkez–Polonya köprüsü",
          "Tescil ve hukuki sonuç taahhüdü yoktur",
        ],
        ctaLabel: "Kuruluş danışmanlığı",
        href: "/hizmetler/kurulum",
      },
      {
        id: "egitim",
        label: "Üniversite",
        title: "Üniversite / eğitim yazışması",
        bullets: [
          "Kurum yazısını yükleyin veya görüşme formu",
          "Ne isteniyor, son tarih, eksik evrak",
          "Aile / aday / kurum arasında dil köprüsü",
          "Kabul veya vize garantisi yok",
        ],
        ctaLabel: "Eğitim yönlendirmesi",
        href: "/hizmetler/egitim",
      },
      {
        id: "eslik",
        label: "Yerinde eşlik",
        title: "Ehliyet, oturum, urząd — şahıs",
        bullets: [
          "Firma veya şahıs hattı",
          "Ehliyet çevirisi / oturum kartı: checklist, randevu, durum takibi",
          "Uzaktan, telefon veya istenirse yerinde; TR / PL / EN / RU / UK",
          "Onay / kart / ehliyet sonucu garantisi yok",
        ],
        ctaLabel: "Eşlik hizmeti",
        href: "/hizmetler/eslik",
      },
    ],
  },
  scope: {
    eyebrow: "Sınırlar",
    title: "Ne yapıyoruz / ne yapmıyoruz",
    includedTitle: "Yaptığımız",
    excludedTitle: "Yapmadığımız",
    included: [
      "Türkiye’de yerleşik işletmeciler ile Polonya’da faaliyet gösteren Türk ve yabancı sermayeli şirketler için evrak ve idari süreç takibi",
      "Resmi yazının müşteri dilinde özeti; iletişim TR / PL / EN / RU / UK",
      "Türkiye’deki işletmeciler için Polonya yatırım, şirket kuruluşu ve faaliyet — idari danışmanlık ve süreç başlatma (tescil tarafımızca yapılmaz)",
      "Son tarih ve sıradaki adımın net tutulması",
      "Eğitim / üniversite süreçlerinde idari yönlendirme",
      "Polonya’daki KOBİ ve lojistik işletmelerinin faaliyet evrakı takibi; avukat ortağına koordinasyon",
      "Şahıs düzeyinde urząd, ehliyet çevirisi ve oturum kartı süreci — uzaktan, telefon veya yerinde",
      "Talep halinde yerinde idari eşlik",
      "Vekaletli pakette evrak ve randevu koordinasyonu",
      "Avukat ortağı ve muhasebeci ile koordinasyon",
      "Banka hesabı açılışında idari fiili destek (KYC, randevu, dil köprüsü) — açılış veya kredi sonucu garanti edilmez",
      "Ödeme sonrası dosya sayfası ve Hesabım üzerinden durum izleme",
    ],
    excluded: [
      "Şirketi sizin adınıza tescil etmek; KRS / vergi kararı almak",
      "Avukatlık, hukuki tavsiye ve dava",
      "Üniversite kabulü, burs veya vize / oturum garantisi",
      "Banka hesabı açılışı, PESEL, ehliyet veya sağlık sonucu garantisi",
      "Muhasebe ve vergi beyanı / imza",
      "Onay veya süre garantisi",
      "MOS / urząd form otomasyonu",
      "Kendimizi avukat, eğitim aracısı veya yeminli tercüman olarak sunmak",
    ],
  },
  faq: faqTr,
  lead: {
    title: "İletişim",
    intro:
      "İdari takip veya paket için yazın. Hangi paketin size uyduğunu bilmiyorsanız formu doldurun — dönüş genelde bir iş günü. Acil yazı: üst menüden Başvur.",
    fullName: "Ad Soyad",
    company: "Şirket / unvan (isteğe bağlı)",
    employees: "Çalışan sayısı (isteğe bağlı)",
    email: "E-posta",
    phone: "Telefon",
    process: "İlgilendiğiniz hizmet (yaklaşık)",
    processOptions: [
      {
        value: "ticaret-masasi",
        label: "Ticaret danışmanlığı — Polonya",
      },
      { value: "tek-yazi", label: "Tek yazı özeti — satın almadan önce soru" },
      { value: "aylik-paket", label: "Aylık idari takip (abonelik) — önce soru" },
      { value: "surec-yonetimi", label: "Vekaletli idari yürütme — önce soru" },
      { value: "yatirimci", label: "TR işletmeci — Polonya yatırım / şirket kuruluşu" },
      { value: "isletme", label: "KOBİ / lojistik — evrak ve faaliyet masası" },
      {
        value: "egitim",
        label: "Üniversite / eğitim süreç yönlendirme",
      },
      { value: "eslik-firma", label: "Firma — urząd / yerinde eşlik" },
      { value: "eslik-sahis", label: "Şahıs — ehliyet, oturum, urząd" },
      { value: "diger", label: "Diğer / emin değilim" },
    ],
    privacy: "Kişisel verilerimin iletişim amacıyla işlenmesini kabul ediyorum.",
    submit: "Gönder",
    loading: "Gönderiliyor…",
    success:
      "Talebiniz alındı. Ekibimiz e-posta ile dönüş yapacak (genelde 1 iş günü).",
    error: "Gönderilemedi. Lütfen tekrar deneyin.",
    fieldError: "Bu alanı kontrol edin.",
    modalTitle: "İletişim formu",
    close: "Kapat",
  },
  trust: {
    title: "Güven",
    badges: [
      "Avukat değiliz",
      "RODO / gizlilik",
      "Stripe ödeme",
      "Dosya linki (mail eki yok)",
    ],
  },
  footer: {
    disclaimer:
      "ROUTEPOL avukatlık veya mali müşavirlik değildir. Hukuki tavsiye ve temsil Polonyalı avukat ortağındadır. Onay veya süre garantisi vermeyiz.",
    privacy: "Gizlilik",
    rights: "© ROUTEPOL. Tüm hakları saklıdır.",
    servicesHub: "Tüm hizmetler",
    about: "Hakkımızda",
    apply: "Başvur",
    accompaniment: "Yerinde eşlik",
    advisory: "Danışmanlık",
    formation: "Yatırım / kuruluş",
    business: "İşletme hizmetleri",
    education: "Eğitim süreçleri",
    packages: "Paketler",
    guide: "Rehber",
    faq: "SSS",
    groupServices: "Hizmetler",
    groupBuy: "Başvuru",
    groupSite: "Site",
  },
};
